//! CLI generation macro.
//!
//! Generates clap-based CLI applications from impl blocks with automatic command generation.
//!
//! # Command Generation
//!
//! Each method becomes a subcommand:
//! - Method name converted to kebab-case: `create_user` → `create-user`
//! - Doc comments become command descriptions
//! - Parameters become command arguments/options
//!
//! # Mount Points
//!
//! Methods returning `&T` become subcommand groups (mount points):
//! - Static: `fn users(&self) -> &Users` → `app users <subcommand>`
//! - Slug: `fn user(&self, id: UserId) -> &UserService` → `app user <id> <subcommand>`
//!
//! The mounted type must implement `CliSubcommand` (generated by `#[cli]`).
//!
//! # Parameter Mapping
//!
//! - Required parameters → Positional arguments
//! - `Option<T>` parameters → Optional flags (`--name <NAME>`)
//! - `bool` parameters → Boolean flags (`--verbose`)
//!
//! # Generated Methods
//!
//! - `cli_command() -> clap::Command` - Complete CLI application
//! - `cli_run()` - Run from process args
//! - `cli_run_with(args)` - Run with custom args
//!
//! Also implements `CliSubcommand` trait for composition.
//!
//! # Example
//!
//! ```ignore
//! use server_less::cli;
//!
//! struct MyApp;
//!
//! #[cli(name = "myapp", version = "1.0")]
//! impl MyApp {
//!     /// Create a new user
//!     fn create_user(&self, name: String, email: String) {
//!         println!("Creating user: {}", name);
//!     }
//!
//!     /// Delete a user by ID
//!     fn delete_user(&self, id: u32) {
//!         println!("Deleting user: {}", id);
//!     }
//! }
//!
//! // Use it:
//! let app = MyApp;
//! let matches = MyApp::cli_app().get_matches();
//! app.cli_run(&matches);
//! ```
//!
//! # Command Line Usage
//!
//! ```bash
//! myapp create-user "Alice" "alice@example.com"
//! myapp delete-user 123
//! myapp --help
//! ```

use heck::ToKebabCase;

use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use server_less_parse::{MethodInfo, ParamInfo, extract_methods, get_impl_name, partition_methods};
use syn::{ItemImpl, Token, parse::Parse};

// Import Context helpers
use crate::context::{
    generate_cli_context_extraction, has_qualified_context, partition_context_params,
};

/// Arguments for the #[cli] attribute
#[derive(Default)]
pub(crate) struct CliArgs {
    pub name: Option<String>,
    pub version: Option<String>,
    pub about: Option<String>,
    pub global: Vec<String>,
    pub defaults: Option<String>,
}

impl Parse for CliArgs {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        let mut args = CliArgs::default();

        while !input.is_empty() {
            let ident: syn::Ident = input.parse()?;
            input.parse::<Token![=]>()?;

            match ident.to_string().as_str() {
                "name" => {
                    let lit: syn::LitStr = input.parse()?;
                    args.name = Some(lit.value());
                }
                "version" => {
                    let lit: syn::LitStr = input.parse()?;
                    args.version = Some(lit.value());
                }
                "about" => {
                    let lit: syn::LitStr = input.parse()?;
                    args.about = Some(lit.value());
                }
                "global" => {
                    let content;
                    syn::bracketed!(content in input);
                    while !content.is_empty() {
                        let flag: syn::Ident = content.parse()?;
                        args.global.push(flag.to_string());
                        if content.peek(Token![,]) {
                            content.parse::<Token![,]>()?;
                        }
                    }
                }
                "defaults" => {
                    let lit: syn::LitStr = input.parse()?;
                    args.defaults = Some(lit.value());
                }
                other => {
                    return Err(syn::Error::new(
                        ident.span(),
                        format!(
                            "unknown argument `{other}`\n\
                             \n\
                             Valid arguments: name, version, about, global, defaults\n\
                             \n\
                             Example: #[cli(name = \"my-app\", version = \"1.0.0\", about = \"My CLI tool\")]"
                        ),
                    ));
                }
            }

            if input.peek(Token![,]) {
                input.parse::<Token![,]>()?;
            }
        }

        Ok(args)
    }
}

/// Check if a method has `#[cli(skip)]` attribute.
fn has_cli_skip(method: &MethodInfo) -> bool {
    for attr in &method.method.attrs {
        if attr.path().is_ident("cli") {
            // Try parsing as #[cli(skip)]
            let result = attr.parse_nested_meta(|meta| {
                if meta.path.is_ident("skip") {
                    Ok(())
                } else {
                    Err(meta.error("expected `skip`"))
                }
            });
            if result.is_ok() {
                return true;
            }
        }
    }
    false
}

/// Strip `#[cli(...)]` attributes from methods in the impl block so they don't
/// appear in the emitted user code.
fn strip_cli_attrs(impl_block: &ItemImpl) -> ItemImpl {
    let mut block = impl_block.clone();
    for item in &mut block.items {
        if let syn::ImplItem::Fn(method) = item {
            method.attrs.retain(|attr| !attr.path().is_ident("cli"));
        }
    }
    block
}

// partition_methods is now shared from server_less_parse

pub(crate) fn expand_cli(args: CliArgs, impl_block: ItemImpl) -> syn::Result<TokenStream2> {
    let struct_name = get_impl_name(&impl_block)?;
    let methods = extract_methods(&impl_block)?;

    // PASS 1: Scan for qualified server_less::Context usage
    let has_qualified = has_qualified_context(&methods);

    let app_name = args
        .name
        .unwrap_or_else(|| struct_name.to_string().to_kebab_case());
    let version = args.version.unwrap_or_else(|| "0.1.0".to_string());
    let about = args.about.unwrap_or_default();
    let global_flags = args.global;
    let has_defaults = args.defaults.is_some();
    let defaults_fn_ident = args
        .defaults
        .as_ref()
        .map(|name| syn::Ident::new(name, proc_macro2::Span::call_site()));

    let partitioned = partition_methods(&methods, has_cli_skip);

    // Generate subcommands for leaf methods
    let leaf_subcommands: Vec<_> = partitioned
        .leaf
        .iter()
        .map(|m| generate_leaf_subcommand(m, has_qualified, &global_flags, has_defaults))
        .collect::<syn::Result<Vec<_>>>()?;

    // Generate subcommands for static mounts
    let static_mount_subcommands: Vec<_> = partitioned
        .static_mounts
        .iter()
        .map(|m| generate_static_mount_subcommand(m))
        .collect::<syn::Result<Vec<_>>>()?;

    // Generate subcommands for slug mounts
    let slug_mount_subcommands: Vec<_> = partitioned
        .slug_mounts
        .iter()
        .map(|m| generate_slug_mount_subcommand(m, has_qualified))
        .collect::<syn::Result<Vec<_>>>()?;

    // Generate match arms for leaf methods
    let leaf_match_arms: Vec<_> = partitioned
        .leaf
        .iter()
        .map(|m| generate_leaf_match_arm(m, has_qualified, &global_flags, &defaults_fn_ident))
        .collect::<syn::Result<Vec<_>>>()?;

    // Generate match arms for static mounts
    let static_mount_arms: Vec<_> = partitioned
        .static_mounts
        .iter()
        .map(|m| generate_static_mount_arm(m))
        .collect();

    // Generate match arms for slug mounts
    let slug_mount_arms: Vec<_> = partitioned
        .slug_mounts
        .iter()
        .map(|m| generate_slug_mount_arm(m, has_qualified))
        .collect::<syn::Result<Vec<_>>>()?;

    // Strip #[cli(...)] attrs from the emitted impl block
    let clean_impl_block = strip_cli_attrs(&impl_block);

    // Generate global flag args on root command
    let global_flag_args: Vec<_> = global_flags
        .iter()
        .map(|flag| {
            let kebab = flag.replace('_', "-");
            quote! {
                .arg(
                    ::clap::Arg::new(#kebab)
                        .long(#kebab)
                        .action(::clap::ArgAction::SetTrue)
                        .global(true)
                        .help(concat!("Global flag: ", #kebab))
                )
            }
        })
        .collect();

    // Built-in output formatting flags (always present)
    let format_flags = quote! {
        .arg(
            ::clap::Arg::new("jsonl")
                .long("jsonl")
                .action(::clap::ArgAction::SetTrue)
                .global(true)
                .help("Output one JSON object per line (for arrays)")
        )
        .arg(
            ::clap::Arg::new("json")
                .long("json")
                .action(::clap::ArgAction::SetTrue)
                .global(true)
                .help("Output machine-readable JSON")
        )
        .arg(
            ::clap::Arg::new("jq")
                .long("jq")
                .global(true)
                .help("Filter output through jq expression")
        )
    };

    Ok(quote! {
        #clean_impl_block

        impl ::server_less::CliSubcommand for #struct_name {
            fn cli_command() -> ::clap::Command {
                ::clap::Command::new(#app_name)
                    .version(#version)
                    .about(#about)
                    #(#global_flag_args)*
                    #format_flags
                    #(.subcommand(#leaf_subcommands))*
                    #(.subcommand(#static_mount_subcommands))*
                    #(.subcommand(#slug_mount_subcommands))*
            }

            fn cli_dispatch(&self, matches: &::clap::ArgMatches) -> ::std::result::Result<(), Box<dyn ::std::error::Error>> {
                match matches.subcommand() {
                    #(#leaf_match_arms)*
                    #(#static_mount_arms)*
                    #(#slug_mount_arms)*
                    _ => {
                        Self::cli_command().print_help()?;
                        Ok(())
                    }
                }
            }
        }

        impl #struct_name {
            /// Create a clap Command for this CLI
            pub fn cli_command() -> ::clap::Command {
                <Self as ::server_less::CliSubcommand>::cli_command()
            }

            /// Run the CLI application
            pub fn cli_run(&self) -> ::std::result::Result<(), Box<dyn ::std::error::Error>> {
                let matches = Self::cli_command().get_matches();
                <Self as ::server_less::CliSubcommand>::cli_dispatch(self, &matches)
            }

            /// Run the CLI with custom arguments
            pub fn cli_run_with<I, T>(&self, args: I) -> ::std::result::Result<(), Box<dyn ::std::error::Error>>
            where
                I: IntoIterator<Item = T>,
                T: Into<::std::ffi::OsString> + Clone,
            {
                let matches = Self::cli_command().get_matches_from(args);
                <Self as ::server_less::CliSubcommand>::cli_dispatch(self, &matches)
            }
        }
    })
}

fn generate_leaf_subcommand(
    method: &MethodInfo,
    has_qualified: bool,
    global_flags: &[String],
    has_defaults: bool,
) -> syn::Result<TokenStream2> {
    let name = method.name.to_string().to_kebab_case();
    let about = method.docs.clone().unwrap_or_default();

    // Filter out Context parameters - they're injected, not CLI args
    let (_, regular_params) = partition_context_params(&method.params, has_qualified)?;

    // Generate args, skipping params that are global flags
    let args: Vec<_> = regular_params
        .iter()
        .filter(|p| {
            let kebab = p.name.to_string().to_kebab_case();
            !global_flags.iter().any(|g| g.replace('_', "-") == kebab)
        })
        .map(|p| generate_arg(p, global_flags, has_defaults))
        .collect();

    Ok(quote! {
        ::clap::Command::new(#name)
            .about(#about)
            #(.arg(#args))*
    })
}

fn generate_static_mount_subcommand(method: &MethodInfo) -> syn::Result<TokenStream2> {
    let name = method.name.to_string().to_kebab_case();
    let about = method.docs.clone().unwrap_or_default();
    let inner_ty = method.return_info.reference_inner.as_ref().unwrap();

    Ok(quote! {
        {
            let mut __cmd = <#inner_ty as ::server_less::CliSubcommand>::cli_command()
                .name(#name);
            if !#about.is_empty() {
                __cmd = __cmd.about(#about);
            }
            __cmd
        }
    })
}

fn generate_slug_mount_subcommand(
    method: &MethodInfo,
    has_qualified: bool,
) -> syn::Result<TokenStream2> {
    let name = method.name.to_string().to_kebab_case();
    let about = method.docs.clone().unwrap_or_default();
    let inner_ty = method.return_info.reference_inner.as_ref().unwrap();

    let (_, regular_params) = partition_context_params(&method.params, has_qualified)?;

    // Generate positional args for slug params (before subcommands)
    let slug_args: Vec<_> = regular_params
        .iter()
        .enumerate()
        .map(|(i, p)| {
            let param_name = p.name.to_string().to_kebab_case();
            let idx = i + 1; // clap indices are 1-based
            quote! {
                ::clap::Arg::new(#param_name)
                    .required(true)
                    .index(#idx)
                    .help(concat!("The ", #param_name))
            }
        })
        .collect();

    Ok(quote! {
        {
            let mut __cmd = <#inner_ty as ::server_less::CliSubcommand>::cli_command()
                .name(#name);
            if !#about.is_empty() {
                __cmd = __cmd.about(#about);
            }
            #(__cmd = __cmd.arg(#slug_args);)*
            __cmd
        }
    })
}

fn generate_arg(param: &ParamInfo, _global_flags: &[String], has_defaults: bool) -> TokenStream2 {
    let name = param.name.to_string().to_kebab_case();

    if param.is_bool {
        quote! {
            ::clap::Arg::new(#name)
                .long(#name)
                .action(::clap::ArgAction::SetTrue)
                .help(concat!("Enable ", #name))
        }
    } else if param.is_vec {
        quote! {
            ::clap::Arg::new(#name)
                .long(#name)
                .action(::clap::ArgAction::Append)
                .value_delimiter(',')
                .required(false)
                .help(concat!("Repeatable: ", #name))
        }
    } else if param.is_id {
        let required = !param.is_optional;
        quote! {
            ::clap::Arg::new(#name)
                .required(#required)
                .index(1)
                .help(concat!("The ", #name))
        }
    } else if param.is_optional {
        quote! {
            ::clap::Arg::new(#name)
                .long(#name)
                .required(false)
                .help(concat!("Optional: ", #name))
        }
    } else {
        let required = !has_defaults;
        quote! {
            ::clap::Arg::new(#name)
                .long(#name)
                .required(#required)
                .help(concat!("Required: ", #name))
        }
    }
}

fn generate_leaf_match_arm(
    method: &MethodInfo,
    has_qualified: bool,
    global_flags: &[String],
    defaults_fn_ident: &Option<syn::Ident>,
) -> syn::Result<TokenStream2> {
    let subcommand_name = method.name.to_string().to_kebab_case();
    let method_name = &method.name;

    // Partition Context vs regular parameters
    let (context_param, regular_params) = partition_context_params(&method.params, has_qualified)?;

    let mut arg_extractions = Vec::new();
    let mut arg_names = Vec::new();

    // Generate Context extraction if needed
    if context_param.is_some() {
        let (_extraction, call) = generate_cli_context_extraction();
        arg_extractions.push(quote! {
            let __ctx = #call;
        });
        arg_names.push(quote! { __ctx });
    }

    // Generate regular parameter extractions
    for p in &regular_params {
        let name = &p.name;
        let name_str = p.name.to_string().to_kebab_case();

        // Check if this param is a global flag (extract from root matches)
        let is_global = global_flags.iter().any(|g| g.replace('_', "-") == name_str);

        if p.is_bool {
            if is_global {
                // Global flags: clap propagates them into sub_matches
                arg_extractions.push(quote! {
                    let #name: bool = sub_matches.get_flag(#name_str);
                });
            } else {
                arg_extractions.push(quote! {
                    let #name: bool = sub_matches.get_flag(#name_str);
                });
            }
        } else if p.is_vec {
            arg_extractions.push(quote! {
                let #name: Vec<String> = sub_matches
                    .get_many::<String>(#name_str)
                    .map(|vs| vs.cloned().collect())
                    .unwrap_or_default();
            });
        } else if p.is_optional {
            let ty = &p.ty;
            arg_extractions.push(quote! {
                let #name: #ty = sub_matches
                    .get_one::<String>(#name_str)
                    .and_then(|s| s.parse().ok());
            });
        } else if let Some(defaults_fn) = defaults_fn_ident {
            let ty = &p.ty;
            arg_extractions.push(quote! {
                let #name: #ty = if let Some(__val) = sub_matches.get_one::<String>(#name_str) {
                    __val.parse()?
                } else if let Some(__default) = self.#defaults_fn(#name_str) {
                    __default.parse()?
                } else {
                    return Err(format!("Missing required argument: {}", #name_str).into());
                };
            });
        } else {
            let ty = &p.ty;
            arg_extractions.push(quote! {
                let #name: #ty = sub_matches
                    .get_one::<String>(#name_str)
                    .map(|s| s.parse())
                    .transpose()?
                    .ok_or_else(|| format!("Missing required argument: {}", #name_str))?;
            });
        }
        arg_names.push(quote! { #name });
    }

    let call = if method.return_info.is_unit {
        if method.is_async {
            quote! {
                ::tokio::runtime::Runtime::new()
                    .expect("Failed to create Tokio runtime")
                    .block_on(self.#method_name(#(#arg_names),*));
            }
        } else {
            quote! {
                self.#method_name(#(#arg_names),*);
            }
        }
    } else if method.is_async {
        quote! {
            let result = ::tokio::runtime::Runtime::new()
                .expect("Failed to create Tokio runtime")
                .block_on(self.#method_name(#(#arg_names),*));
        }
    } else {
        quote! {
            let result = self.#method_name(#(#arg_names),*);
        }
    };

    // Extract output format flags
    let format_extraction = quote! {
        let __jsonl = sub_matches.get_flag("jsonl");
        let __json = sub_matches.get_flag("json");
        let __jq: Option<&String> = sub_matches.get_one::<String>("jq");
    };

    let output = if method.return_info.is_unit {
        quote! { println!("Done"); }
    } else if method.return_info.is_result {
        quote! {
            match result {
                Ok(value) => {
                    let __formatted = ::server_less::cli_format_output(
                        ::server_less::serde_json::to_value(&value)?,
                        __jsonl, __json, __jq.map(|s| s.as_str()),
                    )?;
                    println!("{}", __formatted);
                }
                Err(err) => {
                    eprintln!("Error: {:?}", err);
                    ::std::process::exit(1);
                }
            }
        }
    } else if method.return_info.is_option {
        quote! {
            match result {
                Some(value) => {
                    let __formatted = ::server_less::cli_format_output(
                        ::server_less::serde_json::to_value(&value)?,
                        __jsonl, __json, __jq.map(|s| s.as_str()),
                    )?;
                    println!("{}", __formatted);
                }
                None => {
                    eprintln!("Not found");
                    ::std::process::exit(1);
                }
            }
        }
    } else {
        quote! {
            let __formatted = ::server_less::cli_format_output(
                ::server_less::serde_json::to_value(&result)?,
                __jsonl, __json, __jq.map(|s| s.as_str()),
            )?;
            println!("{}", __formatted);
        }
    };

    Ok(quote! {
        Some((#subcommand_name, sub_matches)) => {
            #(#arg_extractions)*
            #call
            #format_extraction
            #output
            Ok(())
        }
    })
}

fn generate_static_mount_arm(method: &MethodInfo) -> TokenStream2 {
    let subcommand_name = method.name.to_string().to_kebab_case();
    let method_name = &method.name;
    let inner_ty = method.return_info.reference_inner.as_ref().unwrap();

    quote! {
        Some((#subcommand_name, sub_matches)) => {
            let __delegate = self.#method_name();
            <#inner_ty as ::server_less::CliSubcommand>::cli_dispatch(__delegate, sub_matches)
        }
    }
}

fn generate_slug_mount_arm(method: &MethodInfo, has_qualified: bool) -> syn::Result<TokenStream2> {
    let subcommand_name = method.name.to_string().to_kebab_case();
    let method_name = &method.name;
    let inner_ty = method.return_info.reference_inner.as_ref().unwrap();

    let (_, regular_params) = partition_context_params(&method.params, has_qualified)?;

    let mut slug_extractions = Vec::new();
    let mut slug_names = Vec::new();

    for p in regular_params {
        let name = &p.name;
        let name_str = p.name.to_string().to_kebab_case();
        let ty = &p.ty;

        slug_extractions.push(quote! {
            let #name: #ty = sub_matches
                .get_one::<String>(#name_str)
                .map(|s| s.parse())
                .transpose()?
                .ok_or_else(|| format!("Missing required argument: {}", #name_str))?;
        });
        slug_names.push(quote! { #name });
    }

    Ok(quote! {
        Some((#subcommand_name, sub_matches)) => {
            #(#slug_extractions)*
            let __delegate = self.#method_name(#(#slug_names),*);
            <#inner_ty as ::server_less::CliSubcommand>::cli_dispatch(__delegate, sub_matches)
        }
    })
}
