//! CLI generation macro.
//!
//! Generates clap-based CLI applications from impl blocks with automatic command generation.
//!
//! # Command Generation
//!
//! Each method becomes a subcommand:
//! - Method name converted to kebab-case: `create_user` → `create-user`
//! - Doc comments become command descriptions
//! - Parameters become command arguments/options
//!
//! # Mount Points
//!
//! Methods returning `&T` become subcommand groups (mount points):
//! - Static: `fn users(&self) -> &Users` → `app users <subcommand>`
//! - Slug: `fn user(&self, id: UserId) -> &UserService` → `app user <id> <subcommand>`
//!
//! The mounted type must implement `CliSubcommand` (generated by `#[cli]`).
//!
//! # Parameter Mapping
//!
//! - Required parameters → Positional arguments
//! - `Option<T>` parameters → Optional flags (`--name <NAME>`)
//! - `bool` parameters → Boolean flags (`--verbose`)
//!
//! # Generated Methods
//!
//! **Sync entrypoints** (suppressed by `#[cli(no_sync)]`):
//! - `cli_command() -> clap::Command` - Complete CLI application
//! - `cli_run()` - Run from process args using an internally-created Tokio runtime
//! - `cli_run_with(args)` - Run with custom args (same runtime behaviour as `cli_run`)
//!
//! **Async entrypoints** (suppressed by `#[cli(no_async)]`):
//! - `cli_run_async()` - Run from process args; caller supplies the async runtime
//! - `cli_run_with_async(args)` - Run with custom args; caller supplies the async runtime
//!
//! **Trait methods** (always generated, never suppressed):
//! - `cli_dispatch(&self, matches)` - Sync dispatch (part of `CliSubcommand`)
//! - `cli_dispatch_async(&self, matches)` - Async dispatch (part of `CliSubcommand`)
//!
//! The `cli_dispatch` / `cli_dispatch_async` trait methods are never suppressed because
//! they are the integration point used by `#[program]` and other presets for composition.
//!
//! Also implements `CliSubcommand` trait for composition.
//!
//! # Example
//!
//! ```ignore
//! use server_less::cli;
//!
//! struct MyApp;
//!
//! #[cli(name = "myapp", version = "1.0")]
//! impl MyApp {
//!     /// Create a new user
//!     fn create_user(&self, name: String, email: String) {
//!         println!("Creating user: {}", name);
//!     }
//!
//!     /// Delete a user by ID
//!     fn delete_user(&self, id: u32) {
//!         println!("Deleting user: {}", id);
//!     }
//! }
//!
//! // Use it:
//! let app = MyApp;
//! let matches = MyApp::cli_app().get_matches();
//! app.cli_run(&matches);
//! ```
//!
//! # Command Line Usage
//!
//! ```bash
//! myapp create-user "Alice" "alice@example.com"
//! myapp delete-user 123
//! myapp --help
//! ```

use heck::ToKebabCase;

use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use server_less_parse::{
    MethodInfo, ParamInfo, extract_groups, extract_map_type, extract_methods, extract_option_type,
    extract_vec_type, get_impl_name, is_unit_type, partition_methods, resolve_method_group,
};
use syn::{ItemImpl, Token, parse::Parse};

// Import Context helpers
use crate::context::{
    generate_cli_context_extraction, has_qualified_context, partition_context_params,
};
use crate::app::extract_app_meta;
use crate::server_attrs::{has_server_hidden, has_server_skip};

/// Arguments for the #[cli] attribute
#[derive(Default)]
pub(crate) struct CliArgs {
    pub name: Option<String>,
    pub version: Option<String>,
    pub description: Option<String>,
    pub homepage: Option<String>,
    pub global: Vec<(String, Option<String>)>,
    pub defaults: Option<String>,
    /// Suppress the sync convenience entrypoints `cli_run()` and `cli_run_with()`.
    ///
    /// The underlying `CliSubcommand::cli_dispatch()` trait method is **not** suppressed —
    /// it remains on the trait and is used by `#[program]` and other presets for composition.
    /// Use `no_sync` when you want to provide your own sync entrypoint or when you only
    /// use the async path.
    pub no_sync: bool,
    /// Suppress the async convenience entrypoints `cli_run_async()` and `cli_run_with_async()`.
    ///
    /// The underlying `CliSubcommand::cli_dispatch_async()` trait method is **not** suppressed —
    /// it remains on the trait and is used by `#[program]` and other presets for composition.
    /// Use `no_async` when all methods are synchronous and you want to keep the generated
    /// impl free of async items.
    pub no_async: bool,
    /// Config struct type path, e.g. `MyConfig`. When set, a `config` subcommand is generated.
    pub config_ty: Option<syn::Path>,
    /// Name of the generated config subcommand (default: `"config"`).
    pub config_cmd_name: Option<String>,
}

impl Parse for CliArgs {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        let mut args = CliArgs::default();

        while !input.is_empty() {
            let ident: syn::Ident = input.parse()?;

            // Bare flags (no `= value`)
            match ident.to_string().as_str() {
                "no_sync" => {
                    args.no_sync = true;
                    if input.peek(Token![,]) {
                        input.parse::<Token![,]>()?;
                    }
                    continue;
                }
                "no_async" => {
                    args.no_async = true;
                    if input.peek(Token![,]) {
                        input.parse::<Token![,]>()?;
                    }
                    continue;
                }
                _ => {}
            }

            input.parse::<Token![=]>()?;

            match ident.to_string().as_str() {
                "name" => {
                    let lit: syn::LitStr = input.parse()?;
                    args.name = Some(lit.value());
                }
                "version" => {
                    let lit: syn::LitStr = input.parse()?;
                    args.version = Some(lit.value());
                }
                "description" => {
                    let lit: syn::LitStr = input.parse()?;
                    args.description = Some(lit.value());
                }
                "homepage" => {
                    let lit: syn::LitStr = input.parse()?;
                    args.homepage = Some(lit.value());
                }
                "global" => {
                    let content;
                    syn::bracketed!(content in input);
                    while !content.is_empty() {
                        let flag: syn::Ident = content.parse()?;
                        let help = if content.peek(Token![=]) {
                            content.parse::<Token![=]>()?;
                            let lit: syn::LitStr = content.parse()?;
                            Some(lit.value())
                        } else {
                            None
                        };
                        args.global.push((flag.to_string(), help));
                        if content.peek(Token![,]) {
                            content.parse::<Token![,]>()?;
                        }
                    }
                }
                "defaults" => {
                    let lit: syn::LitStr = input.parse()?;
                    args.defaults = Some(lit.value());
                }
                other => {
                    const VALID: &[&str] = &[
                        "name", "version", "description", "homepage", "about", "global",
                        "defaults", "no_sync", "no_async",
                    ];
                    let suggestion = crate::did_you_mean(other, VALID)
                        .map(|s| format!(" — did you mean `{s}`?"))
                        .unwrap_or_default();
                    return Err(syn::Error::new(
                        ident.span(),
                        format!(
                            "unknown argument `{other}`{suggestion}\n\
                             \n\
                             Valid arguments: name, version, description, homepage, global, defaults, no_sync, no_async\n\
                             \n\
                             Example: #[cli(name = \"my-app\", description = \"My CLI tool\")]\n\
                             Bare flags: #[cli(no_sync)] or #[cli(no_async)]\n\
                             \n\
                             Related: #[program] preset (CLI + markdown docs), #[markdown] (standalone docs)"
                        ),
                    ));
                }
            }

            if input.peek(Token![,]) {
                input.parse::<Token![,]>()?;
            }
        }

        Ok(args)
    }
}

/// Check if a method has `#[cli(skip)]` or `#[server(skip)]`.
fn has_cli_skip(method: &MethodInfo) -> bool {
    if has_server_skip(method) {
        return true;
    }
    for attr in &method.method.attrs {
        if attr.path().is_ident("cli") {
            let mut found = false;
            let _ = attr.parse_nested_meta(|meta| {
                if meta.path.is_ident("skip") {
                    found = true;
                }
                if meta.input.peek(syn::Token![=]) {
                    let _: proc_macro2::TokenStream = meta.value()?.parse()?;
                }
                Ok(())
            });
            if found {
                return true;
            }
        }
    }
    false
}

/// Check if a method has `#[cli(default)]`.
fn has_cli_default(method: &MethodInfo) -> bool {
    for attr in &method.method.attrs {
        if attr.path().is_ident("cli") {
            let mut found = false;
            let _ = attr.parse_nested_meta(|meta| {
                if meta.path.is_ident("default") {
                    found = true;
                }
                if meta.input.peek(syn::Token![=]) {
                    let _: proc_macro2::TokenStream = meta.value()?.parse()?;
                }
                Ok(())
            });
            if found {
                return true;
            }
        }
    }
    false
}

/// Check if a method has `#[cli(hidden)]` or `#[server(hidden)]`.
fn has_cli_hidden(method: &MethodInfo) -> bool {
    if has_server_hidden(method) {
        return true;
    }
    for attr in &method.method.attrs {
        if attr.path().is_ident("cli") {
            let mut found = false;
            let _ = attr.parse_nested_meta(|meta| {
                if meta.path.is_ident("hidden") {
                    found = true;
                }
                if meta.input.peek(syn::Token![=]) {
                    let _: proc_macro2::TokenStream = meta.value()?.parse()?;
                }
                Ok(())
            });
            if found {
                return true;
            }
        }
    }
    false
}

/// Extract `#[cli(display_with = "fn_name")]` from a method, if present.
fn get_display_with(method: &MethodInfo) -> Option<syn::Path> {
    for attr in &method.method.attrs {
        if attr.path().is_ident("cli") {
            let mut found = None;
            let result = attr.parse_nested_meta(|meta| {
                if meta.path.is_ident("display_with") {
                    let value = meta.value()?;
                    let lit: syn::LitStr = value.parse()?;
                    found = Some(lit.parse::<syn::Path>()?);
                    Ok(())
                } else {
                    // Skip unrecognized keys; they're handled elsewhere.
                    // Consume the value if present (key = ...) or skip bare flags.
                    if meta.input.peek(Token![=]) {
                        let _: proc_macro2::TokenStream = meta.value()?.parse()?;
                    }
                    Ok(())
                }
            });
            if result.is_ok() {
                return found;
            }
        }
    }
    None
}

/// Build an ordered list of group display names.
///
/// When a registry exists, uses declaration order from `groups(...)`.
/// Only includes groups that have at least one method assigned.
fn build_group_order(
    methods: &[&MethodInfo],
    registry: &Option<server_less_parse::GroupRegistry>,
) -> syn::Result<Vec<String>> {
    match registry {
        Some(reg) => {
            // Use registry declaration order, filtered to groups with methods
            let used: std::collections::HashSet<String> = methods
                .iter()
                .filter_map(|m| m.group.clone())
                .collect();
            Ok(reg
                .groups
                .iter()
                .filter(|(id, _)| used.contains(id))
                .map(|(_, display)| display.clone())
                .collect())
        }
        None => {
            // No registry — resolve_method_group will error if any method has a group,
            // so this path only produces an empty vec.
            for m in methods {
                resolve_method_group(m, registry)?;
            }
            Ok(vec![])
        }
    }
}

/// Strip `#[cli(...)]` and `#[server(...)]` attributes from methods in the
/// impl block so they don't appear in the emitted user code.
fn strip_cli_attrs(impl_block: &ItemImpl) -> ItemImpl {
    let mut block = impl_block.clone();
    // Strip #[server(...)] from impl-level attrs (e.g. groups(...))
    block
        .attrs
        .retain(|attr| !attr.path().is_ident("server"));
    for item in &mut block.items {
        if let syn::ImplItem::Fn(method) = item {
            method
                .attrs
                .retain(|attr| !attr.path().is_ident("cli") && !attr.path().is_ident("server"));
            // Strip #[param(...)] from function parameters
            for input in &mut method.sig.inputs {
                if let syn::FnArg::Typed(pat_type) = input {
                    pat_type.attrs.retain(|attr| !attr.path().is_ident("param"));
                }
            }
        }
    }
    block
}

// partition_methods is now shared from server_less_parse

pub(crate) fn expand_cli(args: CliArgs, mut impl_block: ItemImpl) -> syn::Result<TokenStream2> {
    let app_meta = extract_app_meta(&mut impl_block.attrs);
    let args = CliArgs {
        name: args.name.or(app_meta.name),
        description: args.description.or(app_meta.description),
        version: args.version.or_else(|| app_meta.version.and_then(|v| v)),
        homepage: args.homepage.or(app_meta.homepage),
        ..args
    };

    let struct_name = get_impl_name(&impl_block)?;
    let (impl_generics, _ty_generics, where_clause) = impl_block.generics.split_for_impl();
    let self_ty = &impl_block.self_ty;
    let methods = extract_methods(&impl_block)?;

    // PASS 1: Scan for qualified server_less::Context usage
    let has_qualified = has_qualified_context(&methods);

    let app_name = args
        .name
        .unwrap_or_else(|| struct_name.to_string().to_kebab_case());
    let version_tokens = match args.version {
        Some(ref v) => quote! { #v },
        None => quote! { ::std::env!("CARGO_PKG_VERSION") },
    };
    let about = args.description.unwrap_or_default();
    let global_flags_with_help = args.global;
    let global_flags: Vec<String> = global_flags_with_help
        .iter()
        .map(|(name, _)| name.clone())
        .collect();
    let has_defaults = args.defaults.is_some();
    let defaults_fn_ident = args
        .defaults
        .as_ref()
        .map(|name| syn::Ident::new(name, proc_macro2::Span::call_site()));
    let no_sync = args.no_sync;
    let no_async = args.no_async;

    let partitioned = partition_methods(&methods, has_cli_skip);

    // Resolve method groups
    let group_registry = extract_groups(&impl_block)?;
    let group_order = build_group_order(&partitioned.leaf, &group_registry)?;
    let has_groups = !group_order.is_empty();

    // Generate subcommands for leaf methods.
    // When groups exist, hide all leaf subcommands from clap's help — we render
    // them ourselves via `after_help` because clap doesn't support multiple
    // subcommand sections (clap-rs/clap#1553).
    let leaf_subcommands: Vec<_> = partitioned
        .leaf
        .iter()
        .map(|m| {
            generate_leaf_subcommand(
                m,
                has_qualified,
                &global_flags,
                has_defaults,
                has_cli_hidden(m) || has_groups,
            )
        })
        .collect::<syn::Result<Vec<_>>>()?;

    // Build grouped help text as `after_help` content
    let grouped_after_help = if has_groups {
        #[allow(clippy::type_complexity)]
        let mut sections: Vec<(Option<String>, Vec<(String, String)>)> = Vec::new();

        // Ungrouped leaf methods first
        let mut ungrouped = Vec::new();
        for m in &partitioned.leaf {
            if has_cli_hidden(m) {
                continue;
            }
            if resolve_method_group(m, &group_registry)?.is_none() {
                let name = m.name_str().to_kebab_case();
                let about = m.docs.clone().unwrap_or_default();
                ungrouped.push((name, about));
            }
        }
        // Static mounts
        for m in &partitioned.static_mounts {
            if !has_cli_hidden(m) {
                let name = m.name_str().to_kebab_case();
                let about = m.docs.clone().unwrap_or_default();
                ungrouped.push((name, about));
            }
        }
        // Slug mounts
        for m in &partitioned.slug_mounts {
            if !has_cli_hidden(m) {
                let name = m.name_str().to_kebab_case();
                let about = m.docs.clone().unwrap_or_default();
                ungrouped.push((name, about));
            }
        }
        if !ungrouped.is_empty() {
            sections.push((None, ungrouped));
        }

        // Grouped methods in registry order
        for group in &group_order {
            let mut entries = Vec::new();
            for m in &partitioned.leaf {
                if has_cli_hidden(m) {
                    continue;
                }
                if resolve_method_group(m, &group_registry)?.as_deref() == Some(group.as_str()) {
                    let name = m.name_str().to_kebab_case();
                    let about = m.docs.clone().unwrap_or_default();
                    entries.push((name, about));
                }
            }
            if !entries.is_empty() {
                sections.push((Some(group.clone()), entries));
            }
        }

        // Column width for alignment
        let max_width = sections
            .iter()
            .flat_map(|(_, entries)| entries.iter())
            .map(|(name, _)| name.len())
            .max()
            .unwrap_or(0);

        let mut text = String::new();
        for (heading, entries) in &sections {
            match heading {
                Some(h) => text.push_str(&format!("\x1b[1;4m{h}:\x1b[0m\n")),
                None => text.push_str("\x1b[1;4mCommands:\x1b[0m\n"),
            }
            for (name, about) in entries {
                if about.is_empty() {
                    text.push_str(&format!("  {name}\n"));
                } else {
                    text.push_str(&format!(
                        "  \x1b[1m{name:<width$}\x1b[0m  {about}\n",
                        width = max_width
                    ));
                }
            }
            text.push('\n');
        }

        Some(quote! { .after_help(#text) })
    } else {
        None
    };

    // Generate subcommands for static mounts
    let static_mount_subcommands: Vec<_> = partitioned
        .static_mounts
        .iter()
        .map(|m| generate_static_mount_subcommand(m, has_cli_hidden(m)))
        .collect::<syn::Result<Vec<_>>>()?;

    // Generate subcommands for slug mounts
    let slug_mount_subcommands: Vec<_> = partitioned
        .slug_mounts
        .iter()
        .map(|m| generate_slug_mount_subcommand(m, has_qualified, has_cli_hidden(m)))
        .collect::<syn::Result<Vec<_>>>()?;

    // Find the default action (if any) — the method marked #[cli(default)].
    // It still appears as a normal subcommand AND runs when no subcommand is given.
    // Emit a compile error if more than one method is marked as default.
    let mut default_methods = partitioned.leaf.iter().filter(|m| has_cli_default(m));
    let default_method = default_methods.next();
    if let Some(second) = default_methods.next() {
        let first_name = default_method
            .map(|m| m.method.sig.ident.to_string())
            .unwrap_or_default();
        return Err(syn::Error::new_spanned(
            &second.method.sig.ident,
            format!(
                "only one method may be marked as default; first default is '{first_name}'"
            ),
        ));
    }

    // Parent-level args for the default action so that flags like
    // `app --flag` are parsed (and shown in `app --help`) when no subcommand is specified.
    let default_parent_args: Vec<TokenStream2> = if let Some(dm) = default_method {
        let (_, regular_params) = partition_context_params(&dm.params, has_qualified)?;
        let filtered: Vec<_> = regular_params
            .iter()
            .filter(|p| {
                let kebab = p.name_str().to_kebab_case();
                !global_flags.iter().any(|g| g.replace('_', "-") == kebab)
            })
            .collect();
        let mut pos_idx = 0usize;
        filtered
            .iter()
            .map(|p| {
                let idx = if p.is_positional {
                    pos_idx += 1;
                    Some(pos_idx)
                } else {
                    None
                };
                generate_arg(p, &global_flags, has_defaults, idx)
            })
            .collect()
    } else {
        vec![]
    };

    // None arm: runs the default action when no subcommand is given.
    // `sub_matches = matches` so the same dispatch body works unchanged.
    let default_none_arm: Option<TokenStream2> = if let Some(dm) = default_method {
        Some(generate_leaf_match_arm(
            dm,
            has_qualified,
            &global_flags,
            &defaults_fn_ident,
            true,
            false,
        )?)
    } else {
        None
    };
    let async_default_none_arm: Option<TokenStream2> = if let Some(dm) = default_method {
        Some(generate_leaf_match_arm(
            dm,
            has_qualified,
            &global_flags,
            &defaults_fn_ident,
            true,
            true,
        )?)
    } else {
        None
    };

    // Generate match arms for leaf methods
    let leaf_match_arms: Vec<_> = partitioned
        .leaf
        .iter()
        .map(|m| {
            generate_leaf_match_arm(m, has_qualified, &global_flags, &defaults_fn_ident, false, false)
        })
        .collect::<syn::Result<Vec<_>>>()?;
    let async_leaf_match_arms: Vec<_> = partitioned
        .leaf
        .iter()
        .map(|m| {
            generate_leaf_match_arm(m, has_qualified, &global_flags, &defaults_fn_ident, false, true)
        })
        .collect::<syn::Result<Vec<_>>>()?;

    // Generate match arms for static mounts
    let static_mount_arms: Vec<_> = partitioned
        .static_mounts
        .iter()
        .map(|m| generate_static_mount_arm(m))
        .collect::<syn::Result<Vec<_>>>()?;
    let async_static_mount_arms: Vec<_> = partitioned
        .static_mounts
        .iter()
        .map(|m| generate_static_mount_arm_async(m))
        .collect::<syn::Result<Vec<_>>>()?;

    // Generate match arms for slug mounts
    let slug_mount_arms: Vec<_> = partitioned
        .slug_mounts
        .iter()
        .map(|m| generate_slug_mount_arm(m, has_qualified))
        .collect::<syn::Result<Vec<_>>>()?;
    let async_slug_mount_arms: Vec<_> = partitioned
        .slug_mounts
        .iter()
        .map(|m| generate_slug_mount_arm_async(m, has_qualified))
        .collect::<syn::Result<Vec<_>>>()?;

    // Build subcommand documentation
    let subcommand_docs: Vec<String> = partitioned
        .leaf
        .iter()
        .filter(|m| !has_cli_hidden(m))
        .map(|m| {
            let name = m.name_str().to_kebab_case();
            match &m.docs {
                Some(doc) => format!("- `{name}` — {doc}"),
                None => format!("- `{name}`"),
            }
        })
        .chain(
            partitioned
                .static_mounts
                .iter()
                .filter(|m| !has_cli_hidden(m))
                .map(|m| {
                    let name = m.name_str().to_kebab_case();
                    format!("- `{name}` (subcommand group)")
                }),
        )
        .chain(
            partitioned
                .slug_mounts
                .iter()
                .filter(|m| !has_cli_hidden(m))
                .map(|m| {
                    let name = m.name_str().to_kebab_case();
                    format!("- `{name} <arg>` (subcommand group)")
                }),
        )
        .collect();
    let cli_command_doc = if subcommand_docs.is_empty() {
        "Create a clap Command for this CLI.".to_string()
    } else {
        format!(
            "Create a clap Command for this CLI.\n\n# Subcommands\n\n{}",
            subcommand_docs.join("\n")
        )
    };

    // Emit the impl block only if this is the highest-priority protocol macro present.
    // When multiple protocol macros are stacked, exactly one emits the impl block;
    // others skip it to prevent duplicate method definitions.
    // Emit the impl block only if this is the highest-priority protocol macro present.
    // Keep sibling protocol attrs on the re-emitted impl so the pipeline processes them next.
    // Only strip cli-specific method-level attrs; leave #[http], #[mcp], etc. intact.
    let clean_impl_block = if crate::is_protocol_impl_emitter(&impl_block, "cli") {
        let stripped = strip_cli_attrs(&impl_block);
        quote! { #stripped }
    } else {
        quote! {}
    };

    // Generate global flag args on root command
    let global_flag_args: Vec<_> = global_flags_with_help
        .iter()
        .map(|(flag, help)| {
            let kebab = flag.replace('_', "-");
            let help_clause = help
                .as_deref()
                .map(|h| quote! { .help(#h) })
                .unwrap_or_default();
            quote! {
                .arg(
                    ::server_less::clap::Arg::new(#kebab)
                        .long(#kebab)
                        .action(::server_less::clap::ArgAction::SetTrue)
                        .global(true)
                        #help_clause
                )
            }
        })
        .collect();

    // Built-in output formatting flags (always present)
    let format_flags = quote! {
        .arg(
            ::server_less::clap::Arg::new("jsonl")
                .long("jsonl")
                .action(::server_less::clap::ArgAction::SetTrue)
                .global(true)
                .help("Output one JSON object per line (for arrays)")
        )
        .arg(
            ::server_less::clap::Arg::new("json")
                .long("json")
                .action(::server_less::clap::ArgAction::SetTrue)
                .global(true)
                .help("Output machine-readable JSON")
        )
        .arg(
            ::server_less::clap::Arg::new("jq")
                .long("jq")
                .global(true)
                .help("Filter output through jq expression")
        )
        .arg(
            ::server_less::clap::Arg::new("input-schema")
                .long("input-schema")
                .action(::server_less::clap::ArgAction::SetTrue)
                .global(true)
                .help("Print JSON Schema of the subcommand's input parameters and exit")
        )
        .arg(
            ::server_less::clap::Arg::new("output-schema")
                .long("output-schema")
                .action(::server_less::clap::ArgAction::SetTrue)
                .global(true)
                .help("Print JSON Schema of the subcommand's return type and exit")
        )
        .arg(
            ::server_less::clap::Arg::new("params-json")
                .long("params-json")
                .global(true)
                .help("Provide all parameters as a JSON object instead of individual flags")
        )
    };

    let sync_entrypoints = if !no_sync {
        quote! {
            /// Run the CLI application.
            ///
            /// Parses process arguments and dispatches to the matching method.
            /// Async methods are driven by an internally-created Tokio runtime —
            /// add `tokio` to your dependencies if any methods are `async`.
            ///
            /// If you already have an async runtime or prefer a different one
            /// (async-std, smol, etc.), use [`cli_run_async`] instead and drive
            /// it with your own `#[runtime::main]`.
            pub fn cli_run(&self) -> ::std::result::Result<(), Box<dyn ::std::error::Error>> {
                if ::server_less::tokio::runtime::Handle::try_current().is_ok() {
                    return Err(
                        "cli_run() cannot be called from within an async context (e.g. #[tokio::test] or #[tokio::main]). \\
                         Use cli_run_async() instead.".into()
                    );
                }
                let matches = Self::cli_command().get_matches();
                <Self as ::server_less::CliSubcommand>::cli_dispatch(self, &matches)
            }

            /// Run the CLI with custom arguments.
            ///
            /// Like [`cli_run`] but accepts an iterator of arguments instead of process args.
            /// Useful for testing.
            pub fn cli_run_with<__CliI, __CliArg>(&self, args: __CliI) -> ::std::result::Result<(), Box<dyn ::std::error::Error>>
            where
                __CliI: IntoIterator<Item = __CliArg>,
                __CliArg: Into<::std::ffi::OsString> + Clone,
            {
                if ::server_less::tokio::runtime::Handle::try_current().is_ok() {
                    return Err(
                        "cli_run_with() cannot be called from within an async context (e.g. #[tokio::test] or #[tokio::main]). \\
                         Use cli_run_with_async() instead.".into()
                    );
                }
                let matches = Self::cli_command().get_matches_from(args);
                <Self as ::server_less::CliSubcommand>::cli_dispatch(self, &matches)
            }
        }
    } else {
        quote! {}
    };

    let async_entrypoint = if !no_async {
        quote! {
            /// Run the CLI application asynchronously.
            ///
            /// Parses process arguments and awaits the dispatched method directly,
            /// without creating an internal runtime. Use this when you already have
            /// an async runtime (e.g. `#[tokio::main]` or `async_std::main`).
            pub async fn cli_run_async(&self) -> ::std::result::Result<(), Box<dyn ::std::error::Error>> {
                let matches = Self::cli_command().get_matches();
                <Self as ::server_less::CliSubcommand>::cli_dispatch_async(self, &matches).await
            }

            /// Run the CLI asynchronously with custom arguments.
            ///
            /// Like [`cli_run_async`] but accepts an iterator of arguments instead of process args.
            /// Useful for testing async CLI dispatch.
            pub async fn cli_run_with_async<__CliI, __CliArg>(&self, args: __CliI) -> ::std::result::Result<(), Box<dyn ::std::error::Error>>
            where
                __CliI: IntoIterator<Item = __CliArg>,
                __CliArg: Into<::std::ffi::OsString> + Clone,
            {
                let matches = Self::cli_command().get_matches_from(args);
                <Self as ::server_less::CliSubcommand>::cli_dispatch_async(self, &matches).await
            }
        }
    } else {
        quote! {}
    };

    // Config subcommand — wired in when `config_ty` is provided (via #[program(config = ...)])
    #[cfg(feature = "config")]
    let (config_methods, config_subcommand_addition, config_dispatch_arm) =
        if let Some(ref config_ty) = args.config_ty {
            let cmd_name = args.config_cmd_name.as_deref().unwrap_or("config");
            crate::config_cmd::generate_all(self_ty, config_ty, cmd_name, &app_name)
        } else {
            (quote! {}, quote! {}, quote! {})
        };
    #[cfg(not(feature = "config"))]
    let (config_methods, config_subcommand_addition, config_dispatch_arm) =
        (quote! {}, quote! {}, quote! {});

    Ok(quote! {
        #clean_impl_block

        impl #impl_generics ::server_less::CliSubcommand for #self_ty #where_clause {
            fn cli_command() -> ::server_less::clap::Command {
                ::server_less::clap::Command::new(#app_name)
                    .version(#version_tokens)
                    .about(#about)
                    #(#global_flag_args)*
                    #format_flags
                    #grouped_after_help
                    #(.arg(#default_parent_args))*
                    #(.subcommand(#leaf_subcommands))*
                    #(.subcommand(#static_mount_subcommands))*
                    #(.subcommand(#slug_mount_subcommands))*
                    #config_subcommand_addition
            }

            fn cli_dispatch(&self, matches: &::server_less::clap::ArgMatches) -> ::std::result::Result<(), Box<dyn ::std::error::Error>> {
                match matches.subcommand() {
                    #(#leaf_match_arms)*
                    #(#static_mount_arms)*
                    #(#slug_mount_arms)*
                    #config_dispatch_arm
                    #default_none_arm
                    _ => {
                        Self::cli_command().print_help()?;
                        Ok(())
                    }
                }
            }

            fn cli_dispatch_async<'__a>(
                &'__a self,
                matches: &'__a ::server_less::clap::ArgMatches,
            ) -> impl ::std::future::Future<Output = ::std::result::Result<(), Box<dyn ::std::error::Error>>> + '__a {
                async move {
                    match matches.subcommand() {
                        #(#async_leaf_match_arms)*
                        #(#async_static_mount_arms)*
                        #(#async_slug_mount_arms)*
                        #config_dispatch_arm
                        #async_default_none_arm
                        _ => {
                            Self::cli_command().print_help()?;
                            Ok(())
                        }
                    }
                }
            }
        }

        impl #impl_generics #self_ty #where_clause {
            #[doc = #cli_command_doc]
            pub fn cli_command() -> ::server_less::clap::Command {
                <Self as ::server_less::CliSubcommand>::cli_command()
            }

            #sync_entrypoints
            #async_entrypoint
        }

        #config_methods
    })
}

fn generate_leaf_subcommand(
    method: &MethodInfo,
    has_qualified: bool,
    global_flags: &[String],
    has_defaults: bool,
    hidden: bool,
) -> syn::Result<TokenStream2> {
    let name = method.name_str().to_kebab_case();
    let about = method.docs.clone().unwrap_or_default();
    let hide = hidden.then(|| quote! { .hide(true) });

    // Filter out Context parameters - they're injected, not CLI args
    let (_, regular_params) = partition_context_params(&method.params, has_qualified)?;

    // Generate args, skipping params that are global flags
    let filtered: Vec<_> = regular_params
        .iter()
        .filter(|p| {
            let kebab = p.name_str().to_kebab_case();
            !global_flags.iter().any(|g| g.replace('_', "-") == kebab)
        })
        .collect();
    let mut pos_idx = 0usize;
    let args: Vec<_> = filtered
        .iter()
        .map(|p| {
            let idx = if p.is_positional {
                pos_idx += 1;
                Some(pos_idx)
            } else {
                None
            };
            generate_arg(p, global_flags, has_defaults, idx)
        })
        .collect();

    Ok(quote! {
        ::server_less::clap::Command::new(#name)
            .about(#about)
            #hide
            #(.arg(#args))*
    })
}

fn generate_static_mount_subcommand(
    method: &MethodInfo,
    hidden: bool,
) -> syn::Result<TokenStream2> {
    let name = method.name_str().to_kebab_case();
    let about = method.docs.clone().unwrap_or_default();
    let inner_ty = method.return_info.reference_inner.as_ref().ok_or_else(|| {
        syn::Error::new_spanned(
            &method.method.sig,
            "BUG: mount method must have a reference return type (&T)",
        )
    })?;
    let hide = hidden.then(|| quote! { __cmd = __cmd.hide(true); });

    Ok(quote! {
        {
            let mut __cmd = <#inner_ty as ::server_less::CliSubcommand>::cli_command()
                .name(#name);
            if !#about.is_empty() {
                __cmd = __cmd.about(#about);
            }
            #hide
            __cmd
        }
    })
}

fn generate_slug_mount_subcommand(
    method: &MethodInfo,
    has_qualified: bool,
    hidden: bool,
) -> syn::Result<TokenStream2> {
    let name = method.name_str().to_kebab_case();
    let about = method.docs.clone().unwrap_or_default();
    let inner_ty = method.return_info.reference_inner.as_ref().ok_or_else(|| {
        syn::Error::new_spanned(
            &method.method.sig,
            "BUG: mount method must have a reference return type (&T)",
        )
    })?;
    let hide = hidden.then(|| quote! { __cmd = __cmd.hide(true); });

    let (_, regular_params) = partition_context_params(&method.params, has_qualified)?;

    // Generate positional args for slug params (before subcommands)
    let slug_args: Vec<_> = regular_params
        .iter()
        .enumerate()
        .map(|(i, p)| {
            let param_name = p.name_str().to_kebab_case();
            let idx = i + 1; // clap indices are 1-based
            quote! {
                ::server_less::clap::Arg::new(#param_name)
                    .required(true)
                    .index(#idx)
                    .help(concat!("The ", #param_name))
            }
        })
        .collect();

    Ok(quote! {
        {
            let mut __cmd = <#inner_ty as ::server_less::CliSubcommand>::cli_command()
                .name(#name);
            if !#about.is_empty() {
                __cmd = __cmd.about(#about);
            }
            #hide
            #(__cmd = __cmd.arg(#slug_args);)*
            __cmd
        }
    })
}

/// Map a syn::Type to a JSON Schema `serde_json::json!(...)` token expression.
///
/// Uses AST inspection instead of string matching so that `Vec<String>` → array
/// and `Option<String>` → string (not "null|object").
fn type_to_json_schema(ty: &Option<syn::Type>) -> TokenStream2 {
    let Some(ty) = ty else {
        return quote! { ::server_less::serde_json::json!({"type": "null"}) };
    };
    type_to_json_schema_ty(ty)
}

fn type_to_json_schema_ty(ty: &syn::Type) -> TokenStream2 {
    use syn::{GenericArgument, PathArguments, Type};
    match ty {
        Type::Path(type_path) => {
            let Some(segment) = type_path.path.segments.last() else {
                return quote! { ::server_less::serde_json::json!({"type": "object"}) };
            };
            match segment.ident.to_string().as_str() {
                "String" => quote! { ::server_less::serde_json::json!({"type": "string"}) },
                "i8" | "i16" | "i32" | "i64" | "u8" | "u16" | "u32" | "u64" | "isize"
                | "usize" => quote! { ::server_less::serde_json::json!({"type": "integer"}) },
                "f32" | "f64" => quote! { ::server_less::serde_json::json!({"type": "number"}) },
                "bool" => quote! { ::server_less::serde_json::json!({"type": "boolean"}) },
                "Vec" => {
                    quote! { ::server_less::serde_json::json!({"type": "array", "items": {}}) }
                }
                "HashMap" | "BTreeMap" | "IndexMap" => {
                    quote! { ::server_less::serde_json::json!({"type": "object", "additionalProperties": true}) }
                }
                "Option" => {
                    // Recurse into Option<T> — schema mirrors the inner type
                    if let PathArguments::AngleBracketed(args) = &segment.arguments
                        && let Some(GenericArgument::Type(inner)) = args.args.first()
                    {
                        return type_to_json_schema_ty(inner);
                    }
                    quote! { ::server_less::serde_json::json!({"type": "object"}) }
                }
                _ => quote! { ::server_less::serde_json::json!({"type": "object"}) },
            }
        }
        Type::Reference(r) => {
            if let Type::Path(tp) = r.elem.as_ref()
                && tp.path.is_ident("str")
            {
                quote! { ::server_less::serde_json::json!({"type": "string"}) }
            } else {
                type_to_json_schema_ty(&r.elem)
            }
        }
        Type::Slice(_) => {
            quote! { ::server_less::serde_json::json!({"type": "array", "items": {}}) }
        }
        _ => quote! { ::server_less::serde_json::json!({"type": "object"}) },
    }
}

fn generate_arg(
    param: &ParamInfo,
    _global_flags: &[String],
    _has_defaults: bool,
    positional_index: Option<usize>,
) -> TokenStream2 {
    let name = param.name_str().to_kebab_case();

    let short = param.short_flag.map(|c| quote! { .short(#c) });

    // Compute the leaf type for the value parser (strip Vec<> / Option<> wrappers).
    // SchemaValueParser<T> requires T: JsonSchema + FromStr; for non-enum types it
    // is a transparent pass-through, so emitting it unconditionally is harmless.
    #[cfg(feature = "jsonschema")]
    let value_parser = if param.is_bool {
        quote! {}
    } else {
        let inner: syn::Type = if param.is_vec {
            param.vec_inner.clone().unwrap_or_else(|| param.ty.clone())
        } else if param.is_optional {
            extract_option_type(&param.ty).unwrap_or_else(|| param.ty.clone())
        } else {
            param.ty.clone()
        };
        quote! { .value_parser(::server_less::SchemaValueParser::<#inner>::new()) }
    };
    #[cfg(not(feature = "jsonschema"))]
    let value_parser = quote! {};

    if param.is_bool {
        let help = match &param.help_text {
            Some(text) => quote! { .help(#text) },
            None => quote! { .help(concat!("Enable ", #name)) },
        };
        quote! {
            ::server_less::clap::Arg::new(#name)
                .long(#name)
                #short
                .action(::server_less::clap::ArgAction::SetTrue)
                #help
        }
    } else if param.is_vec {
        let help = match &param.help_text {
            Some(text) => quote! { .help(#text) },
            None => quote! { .help(concat!("Repeatable: ", #name)) },
        };
        quote! {
            ::server_less::clap::Arg::new(#name)
                .long(#name)
                #short
                .action(::server_less::clap::ArgAction::Append)
                .value_delimiter(',')
                .required(false)
                #value_parser
                #help
        }
    } else if param.is_positional {
        let idx = positional_index.unwrap_or(1);
        let help = match &param.help_text {
            Some(text) => quote! { .help(#text) },
            None => quote! { .help(concat!("The ", #name)) },
        };
        quote! {
            ::server_less::clap::Arg::new(#name)
                .required(false)
                .index(#idx)
                #value_parser
                #help
        }
    } else if param.is_optional {
        let help = match &param.help_text {
            Some(text) => quote! { .help(#text) },
            None => quote! { .help(concat!("Optional: ", #name)) },
        };
        quote! {
            ::server_less::clap::Arg::new(#name)
                .long(#name)
                #short
                .required(false)
                #value_parser
                #help
        }
    } else {
        let help = match &param.help_text {
            Some(text) => quote! { .help(#text) },
            None => quote! { .help(concat!("Required: ", #name)) },
        };
        quote! {
            ::server_less::clap::Arg::new(#name)
                .long(#name)
                #short
                .required(false)
                #value_parser
                #help
        }
    }
}

fn generate_leaf_match_arm(
    method: &MethodInfo,
    has_qualified: bool,
    global_flags: &[String],
    defaults_fn_ident: &Option<syn::Ident>,
    // When true: generates `None =>` arm (default action, no subcommand given)
    // with `let sub_matches = matches;` so the body is identical.
    // When false: generates the normal `Some(("name", sub_matches)) =>` arm.
    none_arm: bool,
    // When true: generates async dispatch (`.await` instead of `block_on`).
    for_async: bool,
) -> syn::Result<TokenStream2> {
    let subcommand_name = method.name_str().to_kebab_case();
    let method_name = &method.name;

    // Partition Context vs regular parameters
    let (context_param, regular_params) = partition_context_params(&method.params, has_qualified)?;

    // ── Input schema (compile-time JSON) ──────────────────────────────
    let input_schema = {
        let mut props = Vec::new();
        let mut required = Vec::new();
        for p in &regular_params {
            let name_str = p.name_str();
            let schema = type_to_json_schema(&Some(p.ty.clone()));
            props.push(quote! {
                __props.insert(#name_str.to_string(), #schema);
            });
            if !p.is_optional && !p.is_bool {
                required.push(quote! { #name_str });
            }
        }
        quote! {
            let mut __props = ::server_less::serde_json::Map::new();
            #(#props)*
            let __schema = ::server_less::serde_json::json!({
                "type": "object",
                "properties": ::server_less::serde_json::Value::Object(__props),
                "required": [#(#required),*],
            });
            println!("{}", ::server_less::serde_json::to_string_pretty(&__schema)?);
            return Ok(());
        }
    };

    // ── Output schema ──────────────────────────────────────────────────
    let output_ty = if method.return_info.is_result {
        &method.return_info.ok_type
    } else if method.return_info.is_option {
        &method.return_info.some_type
    } else if method.return_info.is_unit {
        &None
    } else {
        &method.return_info.ty
    };
    // When the `jsonschema` feature is enabled, emit a runtime schemars call so
    // user-defined structs produce full field-level schemas. When disabled, fall
    // back to the compile-time type-string heuristic (primitives only).
    #[cfg(feature = "jsonschema")]
    let output_schema = if let Some(ty) = output_ty {
        quote! {
            let __schema = ::server_less::cli_schema_for::<#ty>();
            println!("{}", ::server_less::serde_json::to_string_pretty(&__schema)?);
            return Ok(());
        }
    } else {
        quote! {
            println!("{{\"type\": \"null\"}}");
            return Ok(());
        }
    };
    #[cfg(not(feature = "jsonschema"))]
    let output_schema = {
        let output_schema_expr = type_to_json_schema(output_ty);
        quote! {
            let __schema = #output_schema_expr;
            println!("{}", ::server_less::serde_json::to_string_pretty(&__schema)?);
            return Ok(());
        }
    };

    // ── Param extraction: normal CLI args ─────────────────────────────
    let mut arg_extractions = Vec::new();
    let mut arg_names = Vec::new();

    // Generate Context extraction if needed
    if context_param.is_some() {
        let (_extraction, call) = generate_cli_context_extraction();
        arg_extractions.push(quote! {
            let __ctx = #call;
        });
        arg_names.push(quote! { __ctx });
    }

    // Generate regular parameter extractions
    for p in &regular_params {
        let name = &p.name;
        let name_str = p.name_str().to_kebab_case();

        // Check if this param is a global flag (extract from root matches)
        let is_global = global_flags.iter().any(|g| g.replace('_', "-") == name_str);

        if p.is_bool {
            if is_global {
                // Global flags: clap propagates them into sub_matches
                arg_extractions.push(quote! {
                    let #name: bool = sub_matches.get_flag(#name_str);
                });
            } else {
                arg_extractions.push(quote! {
                    let #name: bool = sub_matches.get_flag(#name_str);
                });
            }
        } else if p.is_vec {
            // When jsonschema is active, the value_parser stores inner type T directly.
            // Otherwise, values are stored as String and parsed here.
            #[cfg(feature = "jsonschema")]
            {
                let inner = p.vec_inner.as_ref().unwrap_or(&p.ty);
                arg_extractions.push(quote! {
                    let #name = sub_matches
                        .get_many::<#inner>(#name_str)
                        .map(|vs| vs.cloned().collect())
                        .unwrap_or_default();
                });
            }
            #[cfg(not(feature = "jsonschema"))]
            arg_extractions.push(quote! {
                let #name: Vec<String> = sub_matches
                    .get_many::<String>(#name_str)
                    .map(|vs| vs.cloned().collect())
                    .unwrap_or_default();
            });
        } else if p.is_optional {
            let ty = &p.ty;
            // When jsonschema is active, value is stored as inner T; wrap in Option.
            #[cfg(feature = "jsonschema")]
            {
                let inner = extract_option_type(&p.ty).unwrap_or_else(|| p.ty.clone());
                arg_extractions.push(quote! {
                    let #name: #ty = sub_matches
                        .get_one::<#inner>(#name_str)
                        .cloned();
                });
            }
            #[cfg(not(feature = "jsonschema"))]
            arg_extractions.push(quote! {
                let #name: #ty = sub_matches
                    .get_one::<String>(#name_str)
                    .and_then(|s| s.parse().ok());
            });
        } else if let Some(defaults_fn) = defaults_fn_ident {
            let ty = &p.ty;
            // When jsonschema is active, successfully parsed values are stored as T.
            // The defaults path still parses from a string.
            #[cfg(feature = "jsonschema")]
            arg_extractions.push(quote! {
                let #name: #ty = if let Some(__val) = sub_matches.get_one::<#ty>(#name_str) {
                    __val.clone()
                } else if let Some(__default) = self.#defaults_fn(#name_str) {
                    __default.parse()?
                } else {
                    return Err(format!("Missing required argument: {}", #name_str).into());
                };
            });
            #[cfg(not(feature = "jsonschema"))]
            arg_extractions.push(quote! {
                let #name: #ty = if let Some(__val) = sub_matches.get_one::<String>(#name_str) {
                    __val.parse()?
                } else if let Some(__default) = self.#defaults_fn(#name_str) {
                    __default.parse()?
                } else {
                    return Err(format!("Missing required argument: {}", #name_str).into());
                };
            });
        } else {
            let ty = &p.ty;
            // When jsonschema is active, value is stored as T by the value_parser.
            #[cfg(feature = "jsonschema")]
            arg_extractions.push(quote! {
                let #name: #ty = sub_matches
                    .get_one::<#ty>(#name_str)
                    .cloned()
                    .ok_or_else(|| format!("Missing required argument: {}", #name_str))?;
            });
            #[cfg(not(feature = "jsonschema"))]
            arg_extractions.push(quote! {
                let #name: #ty = sub_matches
                    .get_one::<String>(#name_str)
                    .map(|s| s.parse())
                    .transpose()?
                    .ok_or_else(|| format!("Missing required argument: {}", #name_str))?;
            });
        }
        arg_names.push(quote! { #name });
    }

    // ── Param extraction: --params-json ───────────────────────────────
    let mut json_extractions = Vec::new();
    let mut json_arg_names = Vec::new();

    if context_param.is_some() {
        let (_extraction, call) = generate_cli_context_extraction();
        json_extractions.push(quote! {
            let __ctx = #call;
        });
        json_arg_names.push(quote! { __ctx });
    }

    for p in &regular_params {
        let name = &p.name;
        let name_str = p.name_str();
        let ty = &p.ty;

        if p.is_bool {
            json_extractions.push(quote! {
                let #name: bool = __json_obj.get(#name_str)
                    .and_then(|v| v.as_bool())
                    .unwrap_or(false);
            });
        } else if p.is_optional {
            json_extractions.push(quote! {
                let #name: #ty = __json_obj.get(#name_str)
                    .and_then(|v| ::server_less::serde_json::from_value(v.clone()).ok());
            });
        } else if p.is_vec {
            json_extractions.push(quote! {
                let #name: Vec<String> = __json_obj.get(#name_str)
                    .map(|v| ::server_less::serde_json::from_value(v.clone()))
                    .transpose()
                    .map_err(|e| format!("Invalid value for '{}': {}", #name_str, e))?
                    .unwrap_or_default();
            });
        } else {
            json_extractions.push(quote! {
                let #name: #ty = __json_obj.get(#name_str)
                    .ok_or_else(|| format!("Missing required field '{}' in --params-json", #name_str))
                    .and_then(|v| ::server_less::serde_json::from_value(v.clone())
                        .map_err(|e| format!("Invalid value for '{}': {}", #name_str, e)))?;
            });
        }
        json_arg_names.push(quote! { #name });
    }

    // ── Method call ───────────────────────────────────────────────────
    let gen_call = |names: &[TokenStream2]| -> TokenStream2 {
        if method.return_info.is_unit {
            if method.is_async {
                if for_async {
                    quote! { self.#method_name(#(#names),*).await; }
                } else {
                    quote! {
                        ::server_less::tokio::runtime::Runtime::new()?
                            .block_on(self.#method_name(#(#names),*));
                    }
                }
            } else {
                quote! {
                    self.#method_name(#(#names),*);
                }
            }
        } else if method.is_async {
            if for_async {
                quote! { let result = self.#method_name(#(#names),*).await; }
            } else {
                quote! {
                    let result = ::server_less::tokio::runtime::Runtime::new()?
                        .block_on(self.#method_name(#(#names),*));
                }
            }
        } else {
            quote! {
                let result = self.#method_name(#(#names),*);
            }
        }
    };

    let call = gen_call(&arg_names);
    let json_call = gen_call(&json_arg_names);

    // Extract output format flags
    let format_extraction = quote! {
        let __jsonl = sub_matches.get_flag("jsonl");
        let __json = sub_matches.get_flag("json");
        let __jq: Option<&String> = sub_matches.get_one::<String>("jq");
    };

    let display_with = get_display_with(method);

    // Determine the effective inner type for default Display detection
    let inner_ty = if method.return_info.is_result {
        method.return_info.ok_type.as_ref()
    } else if method.return_info.is_option {
        method.return_info.some_type.as_ref()
    } else {
        method.return_info.ty.as_ref()
    };

    // Generate the display logic for a value binding
    let gen_value_display = |value_ident: &syn::Ident| -> TokenStream2 {
        // JSON flags always win; display_with only governs text output
        let text_display = if let Some(ref display_fn) = display_with {
            quote! {
                let __display = self.#display_fn(&#value_ident);
                println!("{}", __display);
            }
        } else if let Some(ty) = inner_ty {
            if is_unit_type(ty) {
                quote! { println!("Done"); }
            } else if extract_vec_type(ty).is_some() {
                quote! {
                    for __item in &#value_ident {
                        println!("{}", __item);
                    }
                }
            } else if extract_map_type(ty).is_some() {
                quote! {
                    for (__k, __v) in &#value_ident {
                        println!("{}: {}", __k, __v);
                    }
                }
            } else {
                quote! { println!("{}", #value_ident); }
            }
        } else {
            quote! { println!("{}", #value_ident); }
        };

        quote! {
            if __json || __jsonl || __jq.is_some() {
                let __formatted = ::server_less::cli_format_output(
                    ::server_less::serde_json::to_value(&#value_ident)?,
                    __jsonl, __json, __jq.map(|s| s.as_str()),
                )?;
                println!("{}", __formatted);
            } else {
                #text_display
            }
        }
    };

    let value_ident = syn::Ident::new("value", proc_macro2::Span::call_site());

    let output = if method.return_info.is_unit {
        quote! { println!("Done"); }
    } else if method.return_info.is_result {
        let display_code = gen_value_display(&value_ident);
        quote! {
            match result {
                Ok(value) => {
                    #display_code
                }
                Err(err) => {
                    eprintln!("{}", err);
                    ::std::process::exit(1);
                }
            }
        }
    } else if method.return_info.is_option {
        let display_code = gen_value_display(&value_ident);
        quote! {
            match result {
                Some(value) => {
                    #display_code
                }
                None => {
                    if __json || __jsonl || __jq.is_some() {
                        let __formatted = ::server_less::cli_format_output(
                            ::server_less::serde_json::Value::Null,
                            __jsonl, __json, __jq.map(|s| s.as_str()),
                        )?;
                        println!("{}", __formatted);
                    } else {
                        eprintln!("Not found");
                        ::std::process::exit(1);
                    }
                }
            }
        }
    } else if method.return_info.is_iterator {
        // Streaming path: avoid collecting the whole iterator into memory.
        // --json and --jq collect first (documented as unsafe for infinite iterators).
        // Default and --jsonl stream one JSON line per item.
        quote! {
            if __json || __jq.is_some() {
                let __collected: Vec<_> = result.collect();
                let __formatted = ::server_less::cli_format_output(
                    ::server_less::serde_json::to_value(&__collected)?,
                    false, __json, __jq.map(|s| s.as_str()),
                )?;
                println!("{}", __formatted);
            } else {
                for __item in result {
                    println!("{}", ::server_less::serde_json::to_string(&__item)?);
                }
            }
        }
    } else {
        let result_ident = syn::Ident::new("result", proc_macro2::Span::call_site());
        let display_code = gen_value_display(&result_ident);
        quote! {
            #display_code
        }
    };

    let arm_body = quote! {
        // Schema flags: print and exit without running the method
        if sub_matches.get_flag("input-schema") {
            #input_schema
        }
        if sub_matches.get_flag("output-schema") {
            #output_schema
        }

        // --params-json: extract all params from JSON blob
        if let Some(__params_json_str) = sub_matches.get_one::<String>("params-json") {
            let __json_obj: ::server_less::serde_json::Value = ::server_less::serde_json::from_str(__params_json_str)
                .map_err(|e| format!("Invalid JSON in --params-json: {}", e))?;
            let __json_obj = __json_obj.as_object()
                .ok_or_else(|| "Expected a JSON object for --params-json".to_string())?;
            #(#json_extractions)*
            #json_call
            #format_extraction
            #output
        } else {
            // Normal CLI arg extraction
            #(#arg_extractions)*
            #call
            #format_extraction
            #output
        }
        Ok(())
    };

    Ok(if none_arm {
        // Default action: no subcommand given — bind `sub_matches` to the
        // parent's ArgMatches (which holds the hidden default-action args).
        quote! {
            None => {
                let sub_matches = matches;
                #arm_body
            }
        }
    } else {
        quote! {
            Some((#subcommand_name, sub_matches)) => {
                #arm_body
            }
        }
    })
}

fn generate_static_mount_arm(method: &MethodInfo) -> syn::Result<TokenStream2> {
    let subcommand_name = method.name_str().to_kebab_case();
    let method_name = &method.name;
    let inner_ty = method.return_info.reference_inner.as_ref().ok_or_else(|| {
        syn::Error::new_spanned(
            &method.method.sig,
            "BUG: mount method must have a reference return type (&T)",
        )
    })?;

    Ok(quote! {
        Some((#subcommand_name, sub_matches)) => {
            let __delegate = self.#method_name();
            <#inner_ty as ::server_less::CliSubcommand>::cli_dispatch(__delegate, sub_matches)
        }
    })
}

fn generate_static_mount_arm_async(method: &MethodInfo) -> syn::Result<TokenStream2> {
    let subcommand_name = method.name_str().to_kebab_case();
    let method_name = &method.name;
    let inner_ty = method.return_info.reference_inner.as_ref().ok_or_else(|| {
        syn::Error::new_spanned(
            &method.method.sig,
            "BUG: mount method must have a reference return type (&T)",
        )
    })?;

    Ok(quote! {
        Some((#subcommand_name, sub_matches)) => {
            let __delegate = self.#method_name();
            <#inner_ty as ::server_less::CliSubcommand>::cli_dispatch_async(__delegate, sub_matches).await
        }
    })
}

fn generate_slug_mount_arm(method: &MethodInfo, has_qualified: bool) -> syn::Result<TokenStream2> {
    let subcommand_name = method.name_str().to_kebab_case();
    let method_name = &method.name;
    let inner_ty = method.return_info.reference_inner.as_ref().ok_or_else(|| {
        syn::Error::new_spanned(
            &method.method.sig,
            "BUG: mount method must have a reference return type (&T)",
        )
    })?;

    let (_, regular_params) = partition_context_params(&method.params, has_qualified)?;

    let mut slug_extractions = Vec::new();
    let mut slug_names = Vec::new();

    for p in regular_params {
        let name = &p.name;
        let name_str = p.name_str().to_kebab_case();
        let ty = &p.ty;

        slug_extractions.push(quote! {
            let #name: #ty = sub_matches
                .get_one::<String>(#name_str)
                .map(|s| s.parse())
                .transpose()?
                .ok_or_else(|| format!("Missing required argument: {}", #name_str))?;
        });
        slug_names.push(quote! { #name });
    }

    Ok(quote! {
        Some((#subcommand_name, sub_matches)) => {
            #(#slug_extractions)*
            let __delegate = self.#method_name(#(#slug_names),*);
            <#inner_ty as ::server_less::CliSubcommand>::cli_dispatch(__delegate, sub_matches)
        }
    })
}

fn generate_slug_mount_arm_async(
    method: &MethodInfo,
    has_qualified: bool,
) -> syn::Result<TokenStream2> {
    let subcommand_name = method.name_str().to_kebab_case();
    let method_name = &method.name;
    let inner_ty = method.return_info.reference_inner.as_ref().ok_or_else(|| {
        syn::Error::new_spanned(
            &method.method.sig,
            "BUG: mount method must have a reference return type (&T)",
        )
    })?;

    let (_, regular_params) = partition_context_params(&method.params, has_qualified)?;

    let mut slug_extractions = Vec::new();
    let mut slug_names = Vec::new();

    for p in regular_params {
        let name = &p.name;
        let name_str = p.name_str().to_kebab_case();
        let ty = &p.ty;

        slug_extractions.push(quote! {
            let #name: #ty = sub_matches
                .get_one::<String>(#name_str)
                .map(|s| s.parse())
                .transpose()?
                .ok_or_else(|| format!("Missing required argument: {}", #name_str))?;
        });
        slug_names.push(quote! { #name });
    }

    Ok(quote! {
        Some((#subcommand_name, sub_matches)) => {
            #(#slug_extractions)*
            let __delegate = self.#method_name(#(#slug_names),*);
            <#inner_ty as ::server_less::CliSubcommand>::cli_dispatch_async(__delegate, sub_matches).await
        }
    })
}
